home/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views
app_name = 'Home'

urlpatterns = [
    path('', views.home, name="home"),
    path('our_work/', views.our_work, name="our_work"),
    path('project_details/<int:pk>', views.project_details, name="project_details"),
    path('about_us/', views.about_us, name="about_us"),
    path('our_process/', views.our_process, name="our_process"),
    path('testimonials/', views.testimonials, name="testimonials"),
    path('contactUs/', views.contact_us, name="contact_us"),
    path('success/', views.submissionSuuccess, name="success"),
    path('faq/', views.faq, name="faq"),
]

prairie_code/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home"))
]

home/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    thumbnail = models.ImageField(upload_to='projects/')
    name = models.CharField(max_length=45)
    link = models.CharField(max_length=75, blank=True)
    motivation = models.TextField(blank=False)
    capabilities = models.TextField(blank=False)
    my_contributions = models.TextField(blank=False)

    def __str__(self):
        return self.name

class ProjectGallery(models.Model):
    image = models.ImageField(upload_to='gallery/')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    caption = models.CharField(max_length=35)

    def __str__(self):
        return str(self.image)

home/forms.py
from django import forms
from django.forms.models import ModelForm


class quoteForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    details = forms.CharField(widget=forms.Textarea)

    def check_spam(self):
        common_spam_keywords = ["href", "https", "click", "http", "www", "//"]

        if self.cleaned_data['details'] is not None:
            for keyword in common_spam_keywords:
                if keyword in self.cleaned_data['details'].lower():
                   return 1
            return self.cleaned_data

home/views.py
from django.shortcuts import render, redirect
from django.template.loader import get_template
from .forms import quoteForm
# Create your views here.
from django import forms
from .models import *
from django.core.mail import send_mail, EmailMultiAlternatives


# Create your views here.


def contact_us(request):
    print("Inside of the contact_us view!")
    if request.method == "POST":
        # get the content that was submitted.
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['e-mail']
        content = request.POST['content']

        # need to group the data and send it in an e-mail format. we will
        # make use of client side logic to ensure that all of the data is
        # valid, perhaps just for the e-mail.
        send_mail(
            "Thank You For Choosing Prairie Code LLC",
            "Hello, We Appreciate you for reaching out to us. A "
            "representative will soon reach out to you.",
            "Don't Reply <do_not_reply@domain.example>",
            [email],
            fail_silently=False,
        )
        plaintext = get_template("email/admin_confirmation.txt")
        content = ({
            'user': first_name + last_name,
            'email': email,
            'details': content
        })

        text_content = plaintext.render(content)

        msg = EmailMultiAlternatives("A New Quote Has Been Created",
                                     text_content,
                                     "Don't Reply <do_not_reply@domain.example>",
                                     ['prairiecodellc@gmail.com'])
        msg.send()

        return redirect('Home:success')

    return render(request, "contact_us.html")


def submissionSuuccess(request):
    return render(request, "formSubmitSuccess.html")


def faq(request):
    return render(request, "faq.html")


def about_us(request):
    return render(request, "about_us.html")


def our_process(request):
    return render(request, "our_process.html")


def testimonials(request):
    return render(request, "testimonials.html")


def our_work(request):
    # get a collection of all, projects.
    projects = Project.objects.all()

    return render(request, "our_work.html", {'projects': projects})


def project_details(request, pk):
    # get the project, based off of the pk that we passed in.
    project = Project.objects.filter(pk=pk).get()

    # if the project has a link, associated with, it pass bool variable to
    # template to create a button underneath image.
    if project.link != "":
        print("The link for this project is: ", project.link)
        link = True
    else:
        link = False

    # query all of the images belonging to this proejct.
    images = ProjectGallery.objects.filter(project_id=pk)
    return render(request, "project_details.html",
                  {'project': project, 'images': images, 'link': link})


def home(request):
    # render the form, and send out a confirmation e-mail with a "Do Not Reply Heading". Send e-mail to self as well.

    if request.method == 'POST':
        # get the form submitted by user.
        form = quoteForm(request.POST)

        # check for spam first.

        if form.is_valid():
            # do form processing such as sending out the e-mail.

            # before we can send out the mail we need to make sure that, the details of the form does not contain any blacklisted forms

            if form.check_spam() == 1:
                found_spam = 1
                return render(request, "index.html",
                              {'form': form, 'found_spam': found_spam})
            else:
                found_spam = 0
                return render(request, "index.html",
                              {'form': form, 'found_spam': found_spam})

            send_mail(
                "Thank You For Choosing Prairie Code LLC",
                "Hello, We Appreciate you for reaching out to us. A representative will soon reach out to you.",
                "Don't Reply <do_not_reply@domain.example>",
                [form.cleaned_data['email']],
                fail_silently=False,
            )

            plaintext = get_template("email/admin_confirmation.txt")
            content = ({
                'user': form.cleaned_data['name'],
                'email': form.cleaned_data['email'],
                'details': form.cleaned_data['details']
            })

            text_content = plaintext.render(content)

            msg = EmailMultiAlternatives("A New Quote Has Been Created",
                                         text_content,
                                         "Don't Reply <do_not_reply@domain.example>",
                                         ['prairiecodellc@gmail.com'])
            msg.send()

            form = quoteForm()

            return redirect('Home:home')

    else:
        # print out the form error in the template itself.

        form = quoteForm()
    return render(request, "index.html", {'form': form, })

home/templates/about_us.html
{% extends 'index.html' %}

{% load static %}



{% block mainbody %}

<section id="about_us">
    <div class="container-fluid p-5">

        <div class="section-header text-center pt-3">
            <h1>What is Prairie Code?</h1>
        </div>

        <div class="row jusityf-content-between">
            <div class="col-sm">
            </div>
            <div class="col-sm">
                <p class="lead fw-bold text-white p-3">Prairie Code is your premier choice for web development.
                    We are based out of Council Bluffs, IA. Prairie Code is deeply rooted with our strong core of
                    values. Which includes: </p>

                <ul class="text-left text-white m-4 lead fw-bold">
                    <li>Enhancing our client's online presence through the design of their websites.</li>
                    <li>Ensuring that the client has an enriching user-experience, through the use of their website.
                    </li>
                    <li>Expecting the best out of ourselves and never settling for less.</li>
                </ul>
            </div>
            <div class="col-sm">
            </div>
        </div>

    </div>
</section>


<section id="captions">
    <div class="row justify-content-between p-5">
        <div class="col-sm text-center facet">
            <div class="container-fluid  p-3 facet-header">
                <h2 class="header">Web Development</h2>
            </div>
            <p class="lead p-5 text-white" style="font-weight: bold;">Utilizing the tools of the trade, we put these
                tools into place to help us perform the many meticulous duties, involved in creating a website.</p>
        </div>

        <div class="col-sm text-center facet">
            <div class="container-fluid p-3 facet-header">
                <h2 class="header">Web Design</h2>
            </div>
            <p class="lead p-5  text-white" style="font-weight: bold;">We utilize your brand and identity in order
                to,
                take these characteristics of your brand and your business in order to design your website. We don't
                want to create the same bland websites. We want your website to scream You!</p>

        </div>

        <div class="col-sm text-center facet">
            <div class="container-fluid  p-3 facet-header">
                <h2 class="header">SEO Optimization</h2>
            </div>
            <p class="lead p-5 text-white" style="font-weight: bold;">A website is most effective when they appear
                in
                the top search results for your particular field. So we aim to improve your search results, so that
                more
                people can discover your website.</p>
        </div>
    </div>
</section>

<section id="about_us">
    <div class="container-fluid p-5">

        <div class="section-header text-center pt-3">
            <h1>Why Choose Us?</h1>
        </div>

        <div class="row jusityf-content-between">
            <div class="col-sm">
            </div>
            <div class="col-sm">

                &nbsp;<p class="lead fw-bold text-white p-3">Prairie Code LLC utilizes only the latest and greatest
                    technologies for building applications. There are many others out there that sell you premium
                    services by utilizing do it yourself technologies such as wordpress, wix, etc.</p>

                &nbsp;<p class="lead fw-bold text-white p-3">Prairie Code builds from the ground up, utilizing the
                    latest and greatest technologies that do not limit us in our creativity to build applications
                    for
                    you and for your business. Our choice of technologies allows us to fully optimize your
                    application/system for security, performance and design aspects. Something that can simply not
                    be
                    done when third-party applications.</p>

            </div>
            <div class="col-sm">
            </div>
        </div>

    </div>
</section>

{% endblock %}

home/templates/formSubmitSuccess.html
{% extends 'index.html' %}
{% load static %}



{% block mainbody %}


<div class="container has-text-centered">
    <img src="https://static.vecteezy.com/system/resources/previews/011/383/944/non_2x/young-girl-holding-a-trophy-3d-character-illustration-free-png.png"
        width="75%" height="75%">
    <article class="message is-success is-half">
        <div class="message-header">
            <p>Hooray!</p>

        </div>
        <div class="message-body">
            You have successfully filled out the "Contact Us" form, a representative will reach out to you shortly. You
            are one step closer to completing the website of your dreams.
        </div>
    </article>
</div>

{% endblock %}

home/templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

{% block head %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="pKEmhkGIUvN9zvKPCbeiwEc9XsDbcOfJzEexyQMxhsc" />
    <title>Prairie Code</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/lightbox.css' %}" rel="stylesheet" type="text/css">


</head>
{% endblock %}

{% block body_settings %}

<body>



    {% endblock %}

    {% block preloader %}
    <div id="preloader">
    </div>

    {% endblock %}

    {% block navigation %}

    <nav class="navbar" role="navigation" aria-label="main navigation" style="background-color: #27374D;">
        <div class="navbar-brand">
            <!-- svg for prairiee leaf code -->

            <a class="navbar-item has-text-white is-size-3" href="{% url 'Home:home' %}" style="font-family: hyperion;">
                <strong>Prairie Code</strong>
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="white"
                    class="bi bi-three-dots-vertical m-4" viewBox="0 0 16 16">
                    <path
                        d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                </svg>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu" style="background-color: #27374D;">
            <div class="navbar-start">
                <a class="navbar-item has-text-white" href="{% url 'Home:our_process' %}">
                    Our Process
                </a>

                <a class="navbar-item has-text-white" href="{% url 'Home:our_work' %}">
                    Our Work
                </a>

                <a class="navbar-item has-text-white" href="{% url 'Home:faq' %}">
                    FAQ
                </a>
                <!--
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link has-text-white">
                        More
                    </a>

                    <div class="navbar-dropdown" style="background-color: #27374D;">
                        <a class="navbar-item has-text-white">
                            About
                        </a>
                        <a class="navbar-item has-text-white">
                            Testimonials
                        </a>
                        <a class="navbar-item has-text-white">
                            Contact
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item has-text-white">
                            Report an issue
                        </a>
                    </div>
                </div>
                -->
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-info" href="{% url 'Home:contact_us' %}">
                            Contact Us
                        </a>

                    </div>
                </div>
            </div>

        </div>
    </nav>
    {% endblock %}
    {% block mainbody %}




    <section id="introduction">
        <div class="columns">
            <div class="column is-half has-text-centered p-5">
                <img src="../static/homePage.gif">
            </div>

            <div class="column is-half" style="padding-top: 5%;  padding-left: 5vw; padding-right: 5vw;">
                <div class="box m-5 pb-5">
                    <p class="text is-size-3 has-text-weight-semibold is-underlined has-text-centered">A Little Bit
                        About Us</p>



                    <div class="container has-text-left">
                        <p class="text has-text-weight-semibold is-size-5">We are an up and coming systems development
                            firm based
                            out
                            of the midwest. We
                            believe that systems are the optimal solution to managing your business in this digital
                            society
                            we live in. We believe that there is no one size fits all or templates to creating a
                            well-rounded system for your business. Through the building of our online systems, we have
                            provided our clients with many different tools and technologies in order to boost their
                            revenue.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="captions" class="pt-5">
        <div class="columns mb-5 mr-5 ml-5 p-3">
            <div class="card column is-half is-offset-one-quarter" style="background-color: #27374D;;">
                <div class="card-content has-text-centered">
                    <p class="title has-text-white">
                        Intuition
                    </p>
                    <p class="subtitle has-text-white">
                        Through each project that we have built we have gained new insight in how we can create
                        the web application of your dreams.
                    </p>
                    <img src="../static/brain.png" width="100" height="100" class="p-2">

                </div>

            </div>
        </div>

        <div class="columns  m-5 p-3">
            <div class="card column is-half is-offset-one-quarter" style="background-color: #27374D;">
                <div class="card-content has-text-centered">
                    <p class="title has-text-white">
                        Innovation
                    </p>
                    <p class="subtitle has-text-white">
                        We are constantly utilizing the latest and
                        greatest technologies and
                        discovering new
                        ways as to how we can greater improve the performance of our applications.
                    </p>
                    <img src="../static/lightbulb.png" width="100" height="100" class="p-2">

                </div>

            </div>
        </div>


        <div class="columns mt-5 ml-5 mr-5 p-3 pb-5">
            <div class="card column is-half is-offset-one-quarter" style="background-color: #27374D;">
                <div class="card-content has-text-centered">
                    <p class="title has-text-white">
                        Inspiration
                    </p>
                    <p class="subtitle has-text-white">
                        Our inspiration is our client, we take our
                        time to understand yourself
                        as well as
                        your companies mission, goals and values. We take all of this and we turn it into our source
                        of
                        inspiration in order to build the product of your dreams
                    </p>

                    <img src="../static/fire.png" width="100" height="100" class="p-2">

                </div>

            </div>
        </div>
    </section>

    <section id="our_techStack">

        <section class="hero is-large pb-5" style="background-color: #526D82;">


            <div class="hero-body pt-5 pl-0 pr-0 pb-5" style="text-align: center;">
                <div class="container">
                    <p class="title has-text-white" id="techStackTitle">
                        Overview
                    </p>
                    <p class="subtitle has-text-white p-5" id="techStackDetails" style="text-align: left;">
                        Hello there my name is Juan Lizarraga-Cortez. I'm a seasoned web developer. So what is it
                        exactly that a web developer does, and what are the different aspects that go into building a
                        sophisticated website? Below I have broken down the process, into 4 main categories, you may
                        click on each of the tasks below to learn a little bit more about each subject.
                    </p>

                    <div id="overviewSection" class="m-0 p-0">
                        <img src="../static/youngJuan.png" height="750" width="550">
                    </div>

                    <div id="frontEndTechnologies" style="display: none;">
                        <img src="https://www.freepnglogos.com/uploads/javascript/logo-html-5-css-javascript-source-code-for-the-taking-23.png"
                            height="650" width="550">
                    </div>

                    <div id="backEndTechnologies" style="display: none;">
                        <img src="../static/python.png" height="250" width="175">
                        <img src="../static/vue.js.png" height="250" width="175">
                        <img src="../static/django-logo.png" height="150" width="125">
                    </div>

                    <div id="hostingTechnologies" style="display: none;">
                        <img src="../static/aws.png" height="750" width="550">
                    </div>

                    <div id="databaseTechnologies" style="display: none;">
                        <img src="../static/mysql.png" height="350" width="250" class="p-0 m-0">
                    </div>
                </div>
            </div>

            <div class="hero-foot">
                <div class="hero-foot">
                    <nav class="tabs is-boxed is-fullwidth">
                        <div class="container" style="overflow-x: auto; overflow-y: hidden;">
                            <ul>
                                <li class="is-active" id="overview">
                                    <a class="" onclick="changeContent('overview')" id="overviewButton"
                                        href="#our_techStack">Overview</a>
                                </li>
                                <li id="front-end">
                                    <a class="has-text-white" onclick="changeContent('front-end')" id="frontEndButton"
                                        href="#our_techStack">Graphical Design</a>
                                </li>
                                <li id="back-end">
                                    <a class="has-text-white" onclick="changeContent('back-end')" id="backEndButton"
                                        href="#our_techStack">Functionality</a>
                                </li>
                                <li id="hosting">
                                    <a class="has-text-white" onclick="changeContent('hosting')" id="hostingButton"
                                        href="#our_techStack">Web
                                        Hosting</a>
                                </li>
                                <li id="database">
                                    <a class="has-text-white" onclick="changeContent('database')" id="databaseButton"
                                        href="#our_techStack">Database</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </section>
    </section>

    {% endblock %}
    {% block footer %}

    <footer class="footer" style="background-color: #27374D;">
        <div class="content has-text-centered">
            <p class="title is-size-4 has-text-white">
                <strong>Prairie Code</strong>

            </p>
        </div>
    </footer>
    {% endblock %}

    <script type="text/javascript">
        $(document).ready(function () {

            // Check for click events on the navbar burger icon
            $(".navbar-burger").click(function () {

                // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                $(".navbar-burger").toggleClass("is-active");
                $(".navbar-menu").toggleClass("is-active");


            });
        });

    </script>
    {% block javascript %}


    <script type="text/javascript">
        var loader = document.getElementById("preloader");
        setTimeout(function () {
            loader.style.display = "none";
        }, 1000);

    </script>



    <script src="{% static 'js/main.js' %}" type="text/javascript"></script>

    {% endblock %}
</body>

</html>

home/templates/our_work.html
{% extends 'index.html' %}
{% load static %}

{% block head %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Our Projects</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link href="../static/css/main.css" rel="stylesheet" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    <style>
        #project_container {
            position: relative;
            height: 45vh;
            width: 70vw;
            display: flex;
            padding-top: 25px;
        }

        .image {
            display: block;
            width: 70vw;
            height: 100%;
        }

        .overlay {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            color: black;
            overflow: hidden;
            width: 100%;
            height: 0;

            transition: .3s ease;
        }

        .container:hover .overlay {
            height: 100%;
        }

        .container:hover img {

            /* Add the blur effect */
            filter: blur(8px);
            -webkit-filter: blur(8px);
        }

        .text {
            /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4);
            /* Black w/opacity/see-through */
            font-size: 25px;
            border-radius: 7px;
            color: white;
            font-weight: bold;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 2;
            width: 80%;
            padding: 20px;
            text-align: center;
        }
    </style>
</head>
{% endblock %}



{% block body_settings %}

<body>


    {% endblock %}


    {% block mainbody %}
    <section id="main_body" style="align-items: center;">

        {% for project in projects %}
        <div class="container" id="project_container">

            <a href="{% url 'Home:project_details' project.id %}">
                <img src="../../media/{{project.thumbnail}}" class="image">
                <div class="overlay">
                    <div class="text">
                        {{project.name}}
                    </div>
                </div>
            </a>


        </div>

        {% endfor %}

    </section>

    {% block javascript %}
    <script>
        var loader = document.getElementById("preloader");
        window.addEventListener("load", function () {
            loader.style.display = "none";

        });
    </script>

    {% endblock %}


    {% endblock %}

home/templates/project_details.html
{% extends 'index.html' %}
{% load static %}

{% block body_settings %}

<body class="bg-dark">

    {% endblock %}
    {% block mainbody %}


    <a href="{% url 'Home:our_work' %}" class="p-3">

        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="black" class="bi bi-grid-3x3-gap"
            viewBox="0 0 16 16">
            <path
                d="M4 2v2H2V2h2zm1 12v-2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm0-5V7a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm0-5V2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm5 10v-2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm0-5V7a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zm0-5V2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1zM9 2v2H7V2h2zm5 0v2h-2V2h2zM4 7v2H2V7h2zm5 0v2H7V7h2zm5 0h-2v2h2V7zM4 12v2H2v-2h2zm5 0v2H7v-2h2zm5 0v2h-2v-2h2zM12 1a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1h-2zm-1 6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V7zm1 4a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1h-2z" />
        </svg>
    </a>



    <div class="section-header has-text-centered pb-5 mt-5 w-100">
        <h1 class="is-size-1"><strong>{{project.name}}</strong></h1>

    </div>
    <!-- insert the thumbnail -->
    <div class="container has-text-centered" style="width: 100%;">
        <img src="../../media/{{project.thumbnail}}" style=" width: 100%;">
        {% if link %}
        <a class="button is-primary p-5 mt-2 fw-bold" target="_blank" href="{{project.link}}">Visit
            Website</a>
        {% endif %}
    </div>

    <div class="content bg-dark rounded" style="margin-left: 15vw; margin-right: 15vw; margin-top: 2vh;">
        <h1 class="text-white text-center text-decoration-underline">About this project</h1>
        <p class="lead text-white fw-bold">{{project.motivation|linebreaksbr}}</p>
    </div>

    <div class="content bg-dark rounded" style="margin-left: 15vw; margin-right: 15vw; margin-top: 2vh;">
        <h1 class="text-white text-decoration-underline text-center">What this project can do.</h1>
        <p class="lead text-white">{{project.capabilities|linebreaksbr}}</p>
    </div>


    <div class="content bg-dark rounded" style="margin-left: 15vw; margin-right: 15vw; margin-top: 2vh; ">
        <h1 class="text-white text-decoration-underline text-center">Skills & Technologies Utilized</h1>
        <ul class="text-white">
            <li>HTML5</li>
            <li>Bootstrap CSS</li>
            <li>Django Web Framework</li>
            <li>Python</li>
            <li>UX/UI Design/Development</li>
        </ul>
    </div>

    <div class="content bg-dark rounded" style="margin-left: 15vw; margin-right: 15vw; margin-top: 2vh; ">
        <h1 class="text-white text-decoration-underline text-center">My Contributions</h1>
        <p class="lead text-white">{{project.my_contributions|linebreaksbr}}</p>
    </div>





    </div>

    <div class="row justify-content-between p-2">


        <section class="has-text-centered">
            <h1 class="is-size-1 has-text-weight-semibold is-underlined">Project Gallery</h1>
        </section>

        <div class="columns is-flex-wrap-wrap p-5">
            {% for image in images %}
            <div class="column is-one-third">
                <a href="/media/{{image}}" data-lightbox="models" data-title="{{image.caption}}">
                    <img src="/media/{{image}}">
                </a>
            </div>

            {% endfor %}
        </div>


        <script type="text/javascript" src="../static/js/lightbox-plus-jquery.js"></script>


        {% endblock %}

home/templates/testimonials.html
{% extends 'index.html' %}
{% load static %}



{% block mainbody %}

<div class="container-fluid mt-5 pt-5">
    <h1 class="heading text-center mt-5 pt-3 text-decoration-underline">See what our recent clients have to say.
    </h1>
</div>


{% endblock %}